# Given two strings s and t.
# String t is generated by random shuffling string s,
# then add one more letter at a random position.
# Return the letter that was added to t.


import unittest


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        def ascii_sum(word: str) -> int:
            result = 0
            for letter in word:
                result += ord(letter)
            return result

        return chr(ascii_sum(t) - ascii_sum(s))


class TestDiff(unittest.TestCase):
    def test_findTheDifference(self):
        solution = Solution()
        self.assertEqual("v", solution.findTheDifference("qwerty", "qwevrty"))
        self.assertEqual("q", solution.findTheDifference("", "q"))


if __name__ == '__main__':
    unittest.main()
